services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/**/Domain/Entity/'

    App\Photo\Infrastructure\Http\PhoenixClient:
      arguments:
        $baseUrl: '%env(PHOENIX_BASE_URL)%'