doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Like:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Like'
                prefix: 'App\Like'
                alias: Like
            Identity:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Identity/Domain/Entity'
                prefix: 'App\Identity\Domain\Entity'
                alias: Identity
            Photo:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Photo/Domain/Entity'
                prefix: 'App\Photo\Domain\Entity'
                alias: Photo

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'
